### ISSUE TITLE
Document write operations in README

### ISSUE THREAD

**Issue by rubensworks** [LDflex/LDflex#10]
Now that #6 has been merged, we should document the usage of the following methods in the README:
* `add`
* `delete`
* `set`
* `replace`

**Comment by scenaristeur** [comment]
Ldflex need updated doc !!!
Please https://forum.solidproject.org/t/remove-friend-403-user-unauthorized/3358

**Comment by RubenVerborgh** [comment]
@scenaristeur All help appreciated.
For instance, in the form of PRs, or https://github.com/sponsors/RubenVerborgh
