### ISSUE TITLE
Get all the resources of a given type

### ISSUE THREAD

**Issue by ccolonna** [LDflex/LDflex#157]
Hi, Is there a way to get all resources of a given type?

I see some issues like : https://github.com/LDflex/LDflex/issues/14
A working example would be super helpful, I found a bit difficult to make it work.

**Comment by jeswr** [comment]
Since [paths](https://github.com/LDflex/LDflex/issues/79) are supported you should be able to do:

```ts
const Person = path.create({ subject: namedNode('https://example.org#Person') });

for await (const person of Person['^rdf:type'])
    console.log(`${person}`);
```
or if you don't have `rdf:` defined in your context
```ts
const Person = path.create({ subject: namedNode('https://example.org#Person') });

for await (const person of Person['^<http://www.w3.org/1999/02/22-rdf-syntax-ns#>'])
    console.log(`${person}`);
```

**Comment by ccolonna** [comment]
Thanks @jeswr , it works like a charm!
