### ISSUE TITLE
Path breaks and resource properties are undefined  

### ISSUE THREAD

**Issue by ccolonna** [LDflex/LDflex#158]
Probably I'm missing something here.

If I do this everything works:

```
async function showAnnotationAndRecording(annotation) {
  console.log(`Spatial Annotation Place: ${await annotation.aboutPlaceName}`)
  console.log(`Spatial Annotation Description: ${await annotation.hasDescription}`)
  const song = path.create({subject: namedNode(await annotation.aboutRecording)})  <=== instantiated a new path
  console.log(`\tabout this song: ${await song.label}`)
  console.log(`\t\tartist: ${await song.hasArtistLabel}`)
  console.log(`\t\ttitle: ${await song.hasTitle}`)
  console.log(`\t\tyoutube id: ${await song.hasYoutubeID}`)
}
```

Here not:

```
async function showAnnotationAndRecordingFailed(annotation) {
    console.log(`Spatial Annotation Place: ${await annotation.aboutPlaceName}`)
    console.log(`Spatial Annotation Description: ${await annotation.hasDescription}`)
    console.log(`\tabout this song: ${await annotation.aboutRecording.label}`)        <===== undefined
    console.log(`\t\tartist: ${await annotation.aboutRecording.hasArtistLabel}`)        <===== undefined
    console.log(`\t\ttitle: ${await annotation.aboutRecording.hasTitle}`)        <===== undefined
    console.log(`\t\tyoutube id: ${await annotation.aboutRecording.hasYoutubeID}`)          <===== undefined
}
```

This are data against I tried this example: [json_ld](https://raw.githubusercontent.com/polifonia-project/sonar2021_demo/develop/src/assets/data/data_v2.jsonld)

Here a working example: [pastebin](https://pastebin.com/3UC4bM3f)

**Comment by jeswr** [comment]
Had a quick look at this an I'm a little bemused - the SPARQL queries that get issued seem to be correct, for instance:
```ts
console.log(`\tabout this song: ${(await annotation.aboutRecording.label.sparql)}`);
```
gives
```sparql
SELECT ?label WHERE {
  <https://w3id.org/polifonia/resource/SpatialAnnotation/00672_recorded_at> <https://w3id.org/polifonia/ON/musical-performance/aboutRecording> ?v0.
  ?v0 <http://www.w3.org/2000/01/rdf-schema#label> ?label.
} 
```
which makes me think that the query engine isn't returning the correct results... I don't have any time to look further into this but maybe one of the original authors may have a better idea of what is going on

**Comment by rubensworks** [comment]
Since `@graph` is used in the JSON-LD document, all triples are wrapped in a (blank) named graph.
Since SPARQL by default only returns results from the default graph, it's normal that the results are empty.

You'd need to either remove the `@graph`, or make the LDflex path apply to a (variable) named graph (which is something that may not be possible yet).
