### ISSUE TITLE
PreloadHandler is  broken because of new way of getting bindings

### ISSUE THREAD

**Issue by danielbeeke** [LDflex/LDflex#323]
If I am correct getting bindings has changed from binding.get('?variable') to binding.get('variable')

It works with the following:
PreloadHandler.js

Line 66:
const result = binding.get(resultVar.substring(1)),

**Comment by jeswr** [comment]
> If I am correct getting bindings has changed from binding.get('?variable') to binding.get('variable')

Ah for Comunica that is correct - and I made corresponding changes in LDflex-comunica some time ago; but not sure how other engines handle it

P.S. I'm assuming you mean this line https://github.com/LDflex/LDflex/blob/b0b433e3c82bf1aaded9cf53f6f5a31793a797e5/src/PreloadHandler.js#L49?

I would accept a PR with a change to this effect
`const result = binding.get(resultVar) ?? binding.get(resultVar).substring(1)`

**Comment by danielbeeke** [comment]
Good, ill make that
