### ISSUE TITLE
Support booleans, numbers, dates as parameters

### ISSUE THREAD

**Issue by RubenVerborgh** [LDflex/LDflex#33]
Currently, methods like `.set`/`.replace`/`.delete` either take a string or a `Term`.

It would be nice if they also supported `true`, `false`, numbers, and dates.

Numbers might be tricky as it is not clear what datatype to cast them to. Booleans are easy.

**Comment by rubensworks** [comment]
For reference, I also needed similar behaviour recently, which is why I implemented this: https://github.com/rubensworks/rdf-literal.js
Only the date-like datatypes are not supported yet.

The other way around (converting `Term` to primitive) may also be useful here.

**Comment by RubenVerborgh** [comment]
Sweet. @rubensworks Any plans of handling the Turtle-/SPARQL-encoding of literals as well?
I had forgotten how much work this was (https://github.com/RubenVerborgh/LDflex/commit/d386880c0377e11375a23660d5087b3bfdb00ba6).

**Comment by rubensworks** [comment]
Not sure if rdf-literal would be the best place for that. As it handles the translation between _JS primitives and RDFJS terms_, but what you need in d386880c0377e11375a23660d5087b3bfdb00ba6 is translation between _RDFJS terms and Turtle/SPARQL terms_. Perhaps [rdf-string](https://github.com/rubensworks/rdf-string.js) would be a better place to implement this encoding (no plans for this, but could make an issue).

**Comment by RubenVerborgh** [comment]
Related: #38
