### ISSUE TITLE
Problem using LDFLex proxy objects with Svelte

### ISSUE THREAD

**Issue by theWebalyst** [LDflex/LDflex#50]
I'm having a problem I don't understand being new to both Svelte and the way LDFlex promises work, but maybe you can help! I'm using LDFlex within a Svelte component to provide a test demo of how to use it with Svelte. I've already got simple demos working along the same lines using rdflib.js, graphy and Rdfjs, but am having a problem with LDFlex.

### Svelte code (TestLDFLex.svelte):
```
<script>
const { PathFactory } = require('ldflex');

// Comunica is needed for SPARQL queries
const { default: ComunicaEngine } = require('ldflex-comunica');
const { namedNode } = require('@rdfjs/data-model');

// The JSON-LD context for resolving properties
const context = {
  "@context": {
	"@vocab": "http://xmlns.com/foaf/0.1/",
	"friends": "knows",
	"label": "http://www.w3.org/2000/01/rdf-schema#label",
  }
};

console.log('Comunica...');
// The query engine and its source
const queryEngine = new ComunicaEngine('https://ruben.verborgh.org/profile/');

console.log('LDFlex...');
// The object that can create new paths
const path = new PathFactory({ context, queryEngine });

const ruben = path.create({ subject: namedNode('https://ruben.verborgh.org/profile/#me') });
</script>

<div><h2>Comunica and LDFlex</h2>
{#await ruben.name}
  <p>Comunica loading...</p>
{:then person}
  <p>Comunica done. LDFlex...</p>
  <p>Person: {person} and Person name: {person.name}</p>
{:catch error}
  <p style="color: red">{error.message}</p>
{/await}
</div>
```
### Browser Displays:
	Comunica and LDFlex
	Comunica done. LDFlex...
	
	Person: Ruben Verborgh and Person name: undefined

**Above is the problem:** `person.name` results in 'undefined'

### Browser debugger:
Breaking at this line:
`<p>Person: {person} and Person name: {person.name}</p>`

Then hover over `person.name` shows:
```
0: Proxy {settings: {…}, subject: NamedNode, proxy: Proxy, extendPath: ƒ}
7: Proxy {settings: {…}, parent: null, subject: Literal, proxy: Proxy, extendPath: ƒ}
length: 8
__proto__: Array(0)
```

Expanding this:
```
0: Proxy
[[Handler]]: PathProxy
[[Target]]: Object
extendPath: ƒ extendPath(newData, parent = this)
proxy: Proxy {settings: {…}, subject: NamedNode, proxy: Proxy, extendPath: ƒ}
settings: {context: {…}, queryEngine: ComunicaEngine, parsedContext: Promise}
subject: NamedNode {value: "https://ruben.verborgh.org/profile/#me"}
__proto__: Object
[[IsRevoked]]: false

7: Proxy
[[Handler]]: PathProxy
[[Target]]: Object
extendPath: ƒ extendPath(newData, parent = this)
parent: null
proxy: Proxy {settings: {…}, parent: null, subject: Literal, proxy: Proxy, extendPath: ƒ}
settings: {context: {…}, queryEngine: ComunicaEngine, parsedContext: Promise}
subject: Literal {id: ""Ruben Verborgh"@en"}
__proto__: Object
[[IsRevoked]]: false
length: 8
__proto__: Array(0)
```

So it looks as if the way LDFlex promises evaluate is not compatible with Svelte, or maybe there's a way around this?

The code is here: https://github.com/theWebalyst/svelte-with-rdf-libs-webpack

**Comment by RubenVerborgh** [comment]
Thanks @theWebalyst, will definitely follow up, as Svelte is high on the list of things I'm curious about regarding Solid development.

Without looking into it, the statement

> So it looks as if the way LDFlex promises evaluate is not compatible with Svelte

would surprise me, as they are regular promises in every way. From what I know about Svelte, it just seems that we are not using them as promises. The line `<p>Person: {person} and Person name: {person.name}</p>` is weird, since `person.name` must be `await`ed, but I don't think it is.

It might take me a couple of days to get to this; if you want to make progress in the meantime, replace things with ordinary promises. I.e., do something like `person = Promise.resolve({ name: Promise.resolve('Test Name') })`. It should work with that first; if it does, I expect LDflex to follow.

**Comment by theWebalyst** [comment]
Thanks Ruben, I'll try your suggestion but there's no hurry.

I might not be doing Svelte correctly and have posted this to their support chat in the hope somebody will chip in. I'll let you know.

**Comment by theWebalyst** [comment]
Closing for now Ruben as this looks like either a Svelte limitation or my code. I created a [REPL](https://svelte.dev/repl/8ae5b09b092843c3afed3aa50ca30fa6?version=3.16.7) and have asked for help on Svelte discord #support. Thanks for helping!
