### ISSUE TITLE
Support multi-property access

### ISSUE THREAD

**Issue by RubenVerborgh** [LDflex/LDflex#52]
At the moment, every property requires its own setter:

```javascript
await data[webId].name.set(name);
await data[webId].nick.set(...nicknames);
```

We could create syntactic sugar for the above, such as:

```javascript
await data[webId].add({ name, nick: nicknames });
```

Whereas a first implementation could simply expand into the two calls above, it would even be nicer to transform then into a single SPARQL query:

```sparql
INSERT DATA {
  <https://ruben.verborgh.org/profile/#me> <http://xmlns.com/foaf/0.1/name> "Ruben Verborgh".
  <https://ruben.verborgh.org/profile/#me> <http://xmlns.com/foaf/0.1/nick> "Ruben".
}
```

That should also work with longer paths such as `data[webId].friends.nick.add('buddy')`.
Furthermore, we want to support `set` and `delete` as well (although deletion likely still requires multiple queries because of how the server is implemented).

Also, we might want to think about adding `get` to do multiproperty _access_, such that `data[webId].get(['name', 'nicknames'])` or `data[webId].get({ name: 'whatever', nick: 'something' })` returns an object `{ name: term, nick: term }`.

Suggested steps:
- [x] Extend `add`/`set`/`delete` handlers to also accept objects and transform them into multiple operations
- [x] Extend SPARQL generation to allow multiple additions in one query (and the `add` handler to make use of it)
- [x] Create `get` handler

**Comment by Vinnl** [comment]
Note to self: once this is release I'll update my cheatsheet for [Adding values for multiple properties](https://vincenttunru.gitlab.io/tripledoc/docs/cheatsheet#ldflex-for-solid-3) and [Reading values for multiple properties](https://vincenttunru.gitlab.io/tripledoc/docs/cheatsheet#ldflex-for-solid-1).

(Sorry for spamming your issue tracker.)
