### ISSUE TITLE
Mutations with property maps fail when conditions are different

### ISSUE THREAD

**Issue by RubenVerborgh** [LDflex/LDflex#60]
As part of #56, we made the assumption that, when a property map is used as argument for a mutation function, [the conditions for all predicates would be the same](https://github.com/LDflex/LDflex/commit/6a247256cd9b1aecd4a9f23fa2b52a086fd1eb6f#diff-267f560c6ff2b91a66eea6abb53f85f5R73).

However, this assumption fails in practice, as there can be 3 different types of conditions:
1. [mutate all](https://github.com/LDflex/LDflex/blob/66759cf546722964880894a97d6111e955d7c656/src/MutationFunctionHandler.js#L66-L70)
2. [mutate some](https://github.com/LDflex/LDflex/blob/66759cf546722964880894a97d6111e955d7c656/src/MutationFunctionHandler.js#L79-L81)
3. [mutate none](https://github.com/LDflex/LDflex/blob/66759cf546722964880894a97d6111e955d7c656/src/MutationFunctionHandler.js#L78)

Now the last case could be eliminated by using the conditions of 1 or 2, but that still leaves two cases instead of the assumed one.

Maybe we should only group mutation expressions that have `predicateObjects`, and return the others as-is? Or is there something better we can do?

**Comment by joachimvh** [comment]
I don't fully understand the problem by looking at the code, can you give an example of a query that is a problem?

**Comment by RubenVerborgh** [comment]
`path.property.delete({ nick: null, name: ['Joachim'],  })`

- The conditions for `nick` are those of `path.property.nick` (mutate all)
- The conditions for `name` are those of `path.property` (mutate some)
- The code will group both together with the conditions of the first
