### ISSUE TITLE
More iteration methods

### ISSUE THREAD

**Issue by jeswr** [LDflex/LDflex#72]
The async (https://caolan.github.io/async/v3/) package has several functionalities that I have found to be useful for iterating over asyncIterable objects when using LDflex (https://github.com/jeswr/LDflex/blob/master/src/IterableMethodsHandler.ts).

This adds methods like `.forEach`, `.every`, `.some`, `.find` etc. and also allows for the option to fine tune whether these operations are run concurrently, in batches, or sequentially.

**Comment by jeswr** [comment]
FYI the unpacked size of the aysnc package is 694 kB

**Comment by jeswr** [comment]
In the meantime I have released some of these handlers here https://github.com/jeswr/ldflex-handlers/

**Comment by rubensworks** [comment]
Those handlers look very useful!

Not sure if they should be present in base LDflex. Keeping it as an addon lib may also make sense.

Perhaps @RubenVerborgh has some more thoughts on this.

**Comment by jeswr** [comment]
Makes sense; though I'd want to migrate it to a more intuitive package name like '@ldflex/iteration-hanlders' or '@jeswr/ldflex-iteration-handlers' (whichever you think it's more suitable; I'm happy to host it under my private user or equally happy to transfer ownership to the LDflex org).

I'd also like to see something along the lines of the `.list` and the `.toRDFPrimitive` handlers that are currently in the aforementioned package to be included in the main lib (it's pretty much just an extension of https://github.com/LDflex/LDflex/issues/39 that handles rdf:seq and rdf:bag as well as rdf:list)

**Comment by rubensworks** [comment]
I'm open to any option.

If @RubenVerborgh agrees, we can definitely transfer your project to this LDflex org.

**Comment by RubenVerborgh** [comment]
Let's do that indeed!

**Comment by jeswr** [comment]
I have version 1 of the library ready to go here [here](https://github.com/jeswr/async-iteration-handlers). It has full test coverage.

I tried requested change of ownership to the LDflex organization in the package settings. I'm not sure if you have received an actionable notification about this (I received an error on my end saying I cannot transfer it as I am not an owner of the LDflex organization).

**Comment by RubenVerborgh** [comment]
Congratulations, new LDflex co-owner @jeswr 😉

Thanks for the hard work!

**Comment by jeswr** [comment]
No worries - ownership has now been transferred.

I've tried to replicate the package structure of the core library as close as possible. You may want to double check the Travis CI configuration as I haven't used it that much.

**Comment by RubenVerborgh** [comment]
We'll need to get rid of Travis, it's blocking us. Example migration at https://github.com/rdfjs/N3.js/commit/521324d2bf034b3c245379d9135780cac59dce5a#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f

**Comment by jeswr** [comment]
Works for me. I'm guessing you would want to move to a collection on native github actions like [this](https://github.com/jeswr/template-typescript/tree/main/.github/workflows)for the CI/CD then?

**Comment by RubenVerborgh** [comment]
@jeswr That's fine, you're a co-owner now, feel free 😉
