### ISSUE TITLE
for await loop is entered twice when returning a single value

### ISSUE THREAD

**Issue by cblakeley** [LDflex/LDflex#78]
Please see https://github.com/LDflex/LDflex/issues/75 for the background to this issue.

Using https://github.com/OpenLinkSoftware/Flexpress as the test app with inputs:
- Data Source URI: https://ruben.verborgh.org/profile/
- Subjects: https://ruben.verborgh.org/profile/#me
- LDflex data path: .name

https://github.com/OpenLinkSoftware/Flexpress/blob/b3b658b1108554a5d76b53e3d722d3e29fa035ff/src/LdFlexClient.js#L234

At LdFlexClient.js:234, if the code is changed to:

```
     // let data = new Set();
      let data = [];
      // setResponsePending(true); // Not required. Response from client-side query engine is very quick.
      for await (const val of resolvedDataPath) {
        // val is not a simple value, it's a Proxy instance
        console.log('val.toString(): ', val.toString());
        // data.add(val.toString());
        data.push(val.toString());
      }
```

once the for await completes, the data array contains two entries: [ "Ruben Verborgh", "Ruben Verborgh" ]. The `for await` loop is entered twice for a single `foaf:name` value.

**Comment by RubenVerborgh** [comment]
There are two values though:

```
:me a foaf:Person;
    foaf:name  "Ruben Verborgh"@en, "Ruben Verborgh"@nl;
```

They will have different `.language` attributes.

So the behavior is correct.
