### ISSUE TITLE
Creating/re-using React Components like https://github.com/solid/react-components

### ISSUE THREAD

**Issue by colin-young** [LDflex/LDflex#83]
I have been able to get a queryEngine set up with local data (see #81), and now I'd like to be able to use that with some React components, similar to how https://github.com/solid/react-components works. It appears from my experiments that that library expects web urls where it fetches the data from. Is there a way to provide my queryEngine to that library so I can reuse the Value, List, etc.?

**Comment by RubenVerborgh** [comment]
Hi @colin-young, that's probably better posted over at solid/react-components.
