### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by jeswr** [LDflex/LDflex#87]
@RubenVerborgh could you create a new release including the patch merged in #86, or add an npm authentication token to the repo's secrets so I can setup an semantic release workflow. 

(I don't have publishing permissions to the ldflex package on npm as it differs to the ldflex org on npm)

**Comment by RubenVerborgh** [comment]
@jeswr You're an npm admin now, does that help?

**Comment by jeswr** [comment]
Yep, thanks!
